### ISSUE TITLE
Q: Model similarity between DeepVariant and DeepPolisher?

### ISSUE THREAD

**Issue by jkalleberg** [google/deeppolisher#1]
Hello,

Am I correctly interpreting DeepPolisher as a blend between DeepVariant + DeepConcensus? Are there any docs, existing or in progress, to illustrate the differences and similarities between the tensors/channels used in the DeepVariant model(s) and the DeepPolisher model? For example, describing how the model listed in the case study here (`/opt/models/pacbio model/checkpoint`) differs from the one listed under the PacBio case study for DeepVariant (`--model_type PACBIO`). 

I have a custom DeepVariant model (WGS & WGS.AF) for my species that we plan to use for polishing Verrko assemblies through traditional variant calling. I assume an Illumina-based DeepVariant model is incompatible as a replacement for the listed DeepPolisher model, but I'd like to understand why. Thanks!

**Comment by kishwarshafin** [comment]
Hi @jkalleberg ,

DeepPolisher is an extension of DeepConsensus. However, it uses a different set of features for predicting a set of errors you see in the assembly. A brief description is provided [here](https://github.com/google/deeppolisher?tab=readme-ov-file#how-it-works).

DeepVariant and DeepPolisher are fundamentally different in the way that DeepVariant uses a candidate-based approach with convolutional neural network (CNN) to find variants where DeepPolisher uses a transformer-based model to predict a sequence. DeepVariant models will not work with DeepPolisher unfortunately.

**Comment by jkalleberg** [comment]
@kishwarshafin Thanks. I understand the incompatibility between the candidate and transformer architecture. But my question could have been worded better. I was referring specifically to the make_examples/make_images steps between the two models, not the underlying predictions made. My confusion is partially because of the similarity between the visuals. The one included in your link breaks down the features in almost the same way the DeepVariant pileup examples are visualized in the docs (for example, [here](https://github.com/google/deepvariant/blob/r1.6/docs/images/hybrid_pileup.png)). The features in DeepPolisher seem more similar to DeepVariant, as opposed to what's included in the workflow diagram for DeepConcensus. 

Another point of confusion is that the case study for DeepPolisher has a lot of similarities with running DeepTrio. For example, DP runs maternal vs paternal inference separately, sort of like how DT stacks the maternal/paternal models in Fig 1 [here](https://www.biorxiv.org/content/10.1101/2021.04.05.438434v1.full). 

I want to understand the evolution of the newer DeepXXX models against the ones I'm already using, but I'm getting confused about how the inputs are pre-processed differently. TIA!

**Comment by kishwarshafin** [comment]
Hi @jkalleberg ,

Yes, it could be a bit confusing to understand. DeepVariant's make_examples create "channels" that are stacked on top of each other as it uses a CNN model. Convolution is a sum operation done through multiple "channels" referred as tensors. A better representation on how channels are stacked can be seen in Figure 1 of the [DeepVariant manuscript](https://www.nature.com/articles/nbt.4235.epdf?author_access_token=q4ZmzqvvcGBqTuKyKgYrQ9RgN0jAjWel9jnR3ZoTv0NuM3saQzpZk8yexjfPUhdFj4zyaA4Yvq0LWBoCYQ4B9vqPuv8e2HHy4vShDgEs8YxI_hLs9ov6Y1f_4fyS7kGZ). 

The make_images of DeepPolisher creates a single matrix of size "bases x features" where we append the features one after another. It's a sequential operation so the model sees features as rows. So all of the features are stacked in a single tensor instead of channels that are stacked on top of each other which you correctly see in the DeepPolisher description. 


In terms of pre-processing:
* DeepVariant only requires reads aligned to the reference to call variants.
* DeepPolisher requires reads phased and mapped to the correct haplotype of a phased genome assembly. Which is done with the pre-processing pipeline called PHARAOH.

Fundamentally, DeepVariant is trained to accurately genotype variants observed against the reference. DeepPolisher is trained to correct errors that happen during the genome assembly process. Although they may seem synonymous, our [previous work](https://www.nature.com/articles/s41592-022-01440-3) showed that we need to be very careful while polishing genome assemblies. So, DeepPolisher tries to simplify the problem by having a sequential model trained to solve the assembly polishing problem.

I hope this gives you some details on the difference.

**Comment by kishwarshafin** [comment]
One more clarifying comment. If you are asking about "types of features" like base, match/mismatch. Then DeepConsensus is designed to work with PacBio subreads. They have unique features like pulse width and duration that are specific to the sequencing technology. DeepPolisher uses reads aligned against the assembly so the features we use to train DeepPolisher uses the features present in read alignment space which is also what DeepVariant has. Which is why DeepPolisher and DeepVariant may seem very similar to you as they share similar features.

**Comment by jkalleberg** [comment]
@kishwarshafin thank you for clarifying! It makes much more sense now. I appreciate the explanation.
